-- MySQL Script generated by MySQL Workbench
-- Fri Sep 12 19:16:32 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accts_and_apps
-- -----------------------------------------------------
USE `accts_and_apps` ;

-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_friends` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_friends` (
  `athlete_id` INT NOT NULL,
  `friend_athlete_id` INT NOT NULL,
  `type` VARCHAR(15) NOT NULL COMMENT 'im_following or following_me')
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
