-- MySQL Script generated by MySQL Workbench
-- Fri Sep 12 19:16:32 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accts_and_apps
-- -----------------------------------------------------
USE `accts_and_apps` ;

-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_activities` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_activities` (
  `athlete_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `activity_type` VARCHAR(10) NOT NULL COMMENT 'run or ride',
  `name` VARCHAR(150) NOT NULL,
  `distance` FLOAT NOT NULL COMMENT 'miles',
  `elevation_gain` FLOAT NOT NULL COMMENT 'in ft',
  `datetime_utc` DATETIME NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_segment_ranks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_segment_ranks` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_segment_ranks` (
  `auth_athlete_id` INT NOT NULL,
  `auth_athlete_rank` INT NOT NULL,
  `other_athlete_id` INT NOT NULL COMMENT 'possible buddy, if rank != 1.',
  `other_athlete_rank` INT NOT NULL COMMENT '1=KOM',
  `segment_id` INT NOT NULL,
  `segment_distance` FLOAT NOT NULL,
  `segment_average_grade` FLOAT NOT NULL COMMENT '%')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accts_and_apps`.`activity_to_segment_id`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`activity_to_segment` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`activity_to_segment` (
  `athlete_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `segment_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
