-- MySQL Script generated by MySQL Workbench
-- Thu Sep 11 22:46:09 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema accts_and_apps
-- -----------------------------------------------------
USE `accts_and_apps` ;

-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_friends` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_friends` (
  `athlete_id` INT NOT NULL,
  `friend_athlete_id` INT NOT NULL,
  `type` VARCHAR(15) NOT NULL COMMENT 'im_following or following_me')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_segments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_segments` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_segments` (
  `segment_id` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL COMMENT 'Run or Ride',
  `distance` FLOAT NOT NULL COMMENT 'miles',
  `average_grade` FLOAT NOT NULL COMMENT 'in %')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accts_and_apps`.`strava_buddies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accts_and_apps`.`strava_buddies` ;

CREATE TABLE IF NOT EXISTS `accts_and_apps`.`strava_buddies` (
  `auth_athlete_id` INT NOT NULL,
  `other_athlete_id` INT NOT NULL COMMENT 'possible buddy, if rank != 1.',
  `segment_id` INT NOT NULL,
  `rank` INT NOT NULL COMMENT '1 = negative control; rank of other',
  `auth_athlete_rank` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
